[package]
name = "AoC2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["cookies"] }
tokio = { version = "1.42.0", features = ["full"] }
